- hosts: localhost
  vars_files:
    - host_vars/demo.yaml
    
  gather_facts: true

  roles:
    # - role: openstack-common
    # - role: openstack-images
    - role: openstack-security-group
    - role: openstack-volume-pilot
    - role: openstack-instance-pilot
    - role: openstack-volume-db
    - role: openstack-instance-db
    # - role: openstack-volume-snapshot
